### ISSUE TITLE
strange warnings while using pacman on runimage

### ISSUE THREAD

**Issue by drishal** [VHSgunzo/runimage#3]
I get these strange warnings on trying to use pacman (shell launched with `OVERFS_MODE=1 runimage.superlite --run-shell`)
```
.
.
.
warning: warning given when extracting /usr/share/locale/ro/LC_TIME/coreutils.mo (Can't set user=0/group=0 for /usr/share/locale/ro/LC_TIME/coreutils.mo)
warning: warning given when extracting /usr/share/locale/ru/LC_MESSAGES/coreutils.mo (Can't set user=0/group=0 for /usr/share/locale/ru/LC_MESSAGES/coreutils.mo)
warning: warning given when extracting /usr/share/locale/ru/LC_TIME/coreutils.mo (Can't set user=0/group=0 for /usr/share/locale/ru/LC_TIME/coreutils.mo)
warning: warning given when extracting /usr/share/locale/sk/LC_MESSAGES/coreutils.mo (Can't set user=0/group=0 for /usr/share/locale/sk/LC_MESSAGES/coreutils.mo)
.
.
.
```
is there any way to resolve these issues?

**Comment by VHSgunzo** [comment]
Hi. These warnings arise due to the fact that `pacman` works in a `fakeroot` environment from an ordinary user, it does not affect anything. If you want, you can run `pacman` with sending stderr to /dev/null (pacman -S ... 2>/dev/null) or you can use `proot -0` for the `fakeroot` environment, but it works more slowly

https://proot-me.github.io
https://github.com/mackyle/fakeroot
