### ISSUE TITLE
Runimage for Artix (Linux) ?

### ISSUE THREAD

**Issue by fwn0** [VHSgunzo/runimage#4]
Hello Maxim,
can you also create bootstrap from artix with dinit ?
I like archlinux, but not systemd. ;)
If you have other more important "homework" and you can not,, would it be possible that you publish recipe as workflows ? I can create bootstrap from artix ( https://gitea.artixlinux.org/artix/artix-bootstrap ), but I can not create your insanely powerful and beautiful runimage.

**Comment by VHSgunzo** [comment]
Hello, in the [next runimage release](https://github.com/VHSgunzo/runimage/blob/v0.39.1), the systemd package has been replaced by the [fake systemd](https://github.com/VHSgunzo/runimage-fake-systemd), but so that all packages that require it do not resent this. 
It was possible to achieve the operability of services inside the container, but some of them still need to be edited.
Also, by default, the systemd of the system (if there is one) will be hidden inside the runimage, but the ability to share systemd is left using the variable `SHARE_SYSTEMD=1`

If you like, I can give you the current [test container](https://huggingface.co/runimage/releases/tree/main/unstable/v0.39.1.23.08.09.121743) of the future runimage release
All changes can be viewed [here](https://github.com/VHSgunzo/runimage/blob/v0.39.1/CHANGELOG.md)

As for the artix bootstrap, I will try to make a test release on it and if there is no problem, perhaps runimage will switch to rootfs from artix.
